export const browserCoreExamples = [
  "Durar browser status",
  "Durar browser start",
  "Durar browser stop",
  "Durar browser tabs",
  "Durar browser open https://example.com",
  "Durar browser focus abcd1234",
  "Durar browser close abcd1234",
  "Durar browser screenshot",
  "Durar browser screenshot --full-page",
  "Durar browser screenshot --ref 12",
  "Durar browser snapshot",
  "Durar browser snapshot --format aria --limit 200",
  "Durar browser snapshot --efficient",
  "Durar browser snapshot --labels",
];

export const browserActionExamples = [
  "Durar browser navigate https://example.com",
  "Durar browser resize 1280 720",
  "Durar browser click 12 --double",
  'Durar browser type 23 "hello" --submit',
  "Durar browser press Enter",
  "Durar browser hover 44",
  "Durar browser drag 10 11",
  "Durar browser select 9 OptionA OptionB",
  "Durar browser upload /tmp/Durar/uploads/file.pdf",
  'Durar browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "Durar browser dialog --accept",
  'Durar browser wait --text "Done"',
  "Durar browser evaluate --fn '(el) => el.textContent' --ref 7",
  "Durar browser console --level error",
  "Durar browser pdf",
];
